// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";

function ReasonComp(Props) {
  var name = Props.name;
  return React.createElement("button", undefined, "Hello " + (name + "!"));
}

var make = ReasonComp;

export {
  make ,
  
}
/* react Not a pure module */
