name: app-lint

on:
  push:
    # paths:
    #   - "packages/app/*"

defaults:
  run:
    working-directory: packages/apps
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Lint
        run: yarn lint
      - name: Run tests
        run: yarn jest
