name: app-lint

on:
  push:
    paths:
      - "packages/app/*"

defaults:
  run:
    working-directory: packages/apps
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Install Packages
        run: yarn install
      - name: Lint
        run: yarn lint